### PR TITLE
Changed ruby_to_generic to always create blocks in the rescue block case

### PR DESCRIPTION
**Pull request by emjin**

### CODE REVIEW

**Comment by emjin** [comment]
Closes #2287 with https://github.com/returntocorp/semgrep/pull/2390

**Comment by aryx** [comment]
It would be useful in the commit message to indicate a Test plan: for other people to be able to reproduce and test your change.
In pfff it can be sometimes just "test plan: make; see also test plan in semgrep related PR".

**Comment by aryx** [comment]
Can be good also in the commit message to reference the issue (you did it in the conversation, but it's better if possible
to do it in the commit message).

**Comment by aryx** [comment]
A nice test plan for example here would be  to show a dump of the AST before and after your fix on a relevant example.

**Pull request merged**
