### PR TITLE
change for issue of matching for multiple assignment.

### PR DESCRIPTION
**Pull request by colleend**
For issue https://github.com/returntocorp/semgrep/issues/1490, the issue filed for Ruby multiple assignment.

### CODE REVIEW

**Comment by aryx** [comment]
You need to reference the issue it relates too.
which semgrep issue this will fixed?

**Comment by colleend** [comment]
> You need to reference the issue it relates too.
> which semgrep issue this will fixed?

oops, my bad -- just added the issue in the comments 👍

**Comment by aryx** [comment]
The problem is that if people want to pattern match on tuple assignments, they will not be able to do so.
Some people may want to match code like
$X, $Y = $Z, and this will not work anymore.

**Comment by aryx** [comment]
I think we should fix that in Generic_vs_generic and when we fail to match a simple assignement,
we can try to go deeper and decompose complex assignment.
@nbrahms @ievans  thoughts?

**Pull request closed without merging**
