### PR TITLE
Add 'Ls' module with safe implementations of List.map etc.

### PR DESCRIPTION
**Pull request by mjambon**
This is a pervasive change and I don't know if I like it, but let's see at least how it affects semgrep's performance.

Before merging, I should at least add some tests.

See also my request to have safe functions by default in the standard library: https://github.com/ocaml/ocaml/issues/10528

### CODE REVIEW

**Comment by aryx** [comment]
At this point, maybe it's just better to switch to Jane Stree Core library which has better defaults?
cc @IagoAbal

**Review by aryx — CHANGES_REQUESTED** [review]
Not  a big fan of that.

**Comment by aryx** [comment]
Or maybe just Jane Stree Base library is enough (Core is a pretty big dependency, but Base is quite small I think).
Seems to have tailrec version of map here:
https://github.com/janestreet/base/blob/master/src/list.ml

**Comment by aryx** [comment]
We would "just" need an 'open Base' at the top of each file.

**Comment by IagoAbal** [comment]
> We would "just" need an 'open Base' at the top of each file.

Actually nowadays you can tell the OCaml compiler to add it for you.

I like Base, but I don't like a lot their obsessive use of labels. If we switch to "raw Base" we would need to fix every place where we call `map func xs` so that it becomes `map ~f:func xs`. Also, Hashtbl's work differently, they are safer, but they have a slightly different semantics so they are not a drop-in replacement (if you try adding a duplicate key it's considered an error). 

When I did use Base I wrapped it to expose a more "classic" interface, and I only used parts of it.

What about just making `Common` safe and prefer `Common` instead of `List`? Or we can rewrite things on-demand and wait for TRMC to magically turn most functions into tail-rec.

Anyways I'm curious to see the perf impact of this even if we don't merge it!

**Comment by mjambon** [comment]
@IagoAbal the performance impact is a ~~12%~~ 41% slowdown according to https://github.com/returntocorp/semgrep/pull/3555#issuecomment-883306152
No it's only that much slower on one of the benchmarks. Here's the log:
```
Baseline: 6.207, Latest: 5.477
Baseline: 1.661, Latest: 1.644
Baseline: 9.712, Latest: 13.732
Potential non-blocking slowdown latest time 13.732 is over 12 percent slower than baseline 9.712. See run output for more details
Baseline: 10.733, Latest: 10.118
Baseline: 1.607, Latest: 1.685
Baseline: 5.586, Latest: 5.668
Baseline: 9.697, Latest: 9.168
Baseline: 7.982, Latest: 7.563
Baseline: 16.077, Latest: 15.878
Baseline: 8.66, Latest: 8.483
Baseline: 5.203, Latest: 5.151
Baseline: 3.379, Latest: 3.531
Baseline: 1.993, Latest: 2.011
Baseline: 3.984, Latest: 3.538
Baseline: 3.173, Latest: 3.065
```

**Comment by aryx** [comment]
Maybe the new Common.map that wrote Iago is enough.

**Pull request closed without merging**
