### PR TITLE
Add Rust support

### PR DESCRIPTION
**Pull request by Ruin0x11**

### CODE REVIEW

**Review by aryx — COMMENTED** [review]
Impressive work.
However it could be better to do it in smaller pieces so we can discuss each part, especially when it comes to AST_generic.ml. The goal of the generic AST is really to try hard to factorize similar constructs in different languages, so we can write one function on the generic AST and it works for all languages. But that means we really try hard to keep the generic AST as minimal as possible. You've added lots of Expr, Stmt, Pat constructs but in many cases we can probably discuss and find an existing equivalent.

**Comment by aryx** [comment]
For example when I added support for Go I refactored lots of things to get a more elegant generic AST while not adding that many new constructors. Of course Rust is a big language, with lots of unique features, but we should still try to keep the generic AST as small as possible (because as you've seen that means later you have to update Meta_AST.ml, IL.ml, AST_to_IL.ml, controlflow.ml, ... which is tedious, so better to add a new constructore in AST_generic.ml when really we have no other options.

**Comment by aryx** [comment]
Could you split this PR in multiple parts? We can get the changes to Lang.ml, and a few other basic stuff first. Later we can have another PR to add stuff in the generic AST for expressions, then stmt, then patterns, etc.
Each in a separate PR would be better for discussioons.

**Review by aryx — APPROVED** [review]
If it's possible, would be better to split the PR and do it in multiple steps.

**Comment by aryx** [comment]
When you feel the need to add a new constructor in AST_generic.ml, it would be great if you could quickly give a reference to the feature and why you're sure there is no equivalent in any other languages.

**Comment by aryx** [comment]
I know it's a lot of additional work for you, but we really care to have a small AST_generic.ml

**Comment by Ruin0x11** [comment]
Sure, here is the new PR. It only touches Lang.ml.

https://github.com/returntocorp/pfff/pull/371

I'm glad working on this piecemeal will lead to better review quality.

**Pull request closed without merging**
