### PR TITLE
Set up pre-commit hook

### PR DESCRIPTION
**Pull request by mjambon**
This adds pre-commit hooks, using the `pre-commit` command like we're already using for the semgrep repo. A major new check is `ocp-indent`. Here's what will happen from now on:

* Each developer should install the pre-commit hooks. This will ensure that committed code is formatted consistently.
* If the developer doesn't do it, CI will fail and will explain how to set things up.

~~The base docker image used in CI will be updated overnight and will then come with the `pre-commit` command.~~
The base docker image used in CI was updated and now comes with the `pre-commit` command.

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
thx for scripts/lint, so simpler to use pre-commit with that.
I never know how to run it in semgrep by myself.

**Comment by aryx** [comment]
Argh, scripts/lint works but I can't commit anymore because pre-commit in the git hook crash with:
```
pad@yrax:~/pfff$ git commit -a -m"foo"
Error processing line 1 of /home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/lib/python3.9/site-packages/_virtualenv.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/lib/python3.9/site-packages/_virtualenv.py", line 40, in <module>
    from functools import partial
ModuleNotFoundError: No module named 'functools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 589, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 572, in main
    known_paths = venv(known_paths)
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 504, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/linuxbrew/.linuxbrew/opt/pre-commit/libexec/bin/../../../../../opt/python@3.9/lib/python3.9/site.py", line 179, in addpackage
    import traceback
ModuleNotFoundError: No module named 'traceback'

```

**Comment by aryx** [comment]
Probably a problem with linuxbrew ...
How did you install python and pre-commit on your machine?
I know we need python 3.7 for semgrep to work.

**Comment by aryx** [comment]
I've copied the one in semgrep/.git/hook/pre-commit in pfff/.git/hook/pre-commit and now it works better.

**Comment by mjambon** [comment]
I haven't tried installing pre-commit with brew. I did ubuntu, docker/ubuntu, docker/alpine. In all cases, pre-commit was installed with `pip3 install pre-commit` after installing python3 and pip3 with the native package manager.

**Pull request merged**
